[package]
name = "duckdb_sqlite_scanner_concurrency_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.30.0", features = ["bundled", "limits"] }
duckdb = { version = "0.9.2", features = ["bundled"]}