[package]
name = "duckdb_sqlite_scanner_concurrency_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.31.0", features = ["bundled", "limits"] }
duckdb = { version = "0.10.1", features = ["bundled"]}